[package]
name = "chad-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
shuttle-runtime = "0.46.0"
tokio = "1.28.2"
serenity = "0.12.2"
tracing = "0.1.40"
anyhow = "1.0.86"
shuttle-serenity = "0.46.0"