[package]
name = "cripto_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { features = ["derive"] }
reqwest = { features = ["blocking", "json"] }
serde_json = {}
strum = {}
strum_macros = {}
tokio = { features = ["macros", "rt-multi-thread"] }
