[package]
name = "cripto_api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
